### ISSUE TITLE
Error in React-Router with <BrowserRouter>

### ISSUE THREAD

**Issue by adityaranjan2005** [RiH-137/Winta-1#4]
The error seems to propagate through React-Router's <BrowserRouter> in react-router-dom. The root cause may be related to undefined Collection but investigating router interaction is needed.

**Comment by adityaranjan2005** [comment]
Suggested the PR

**Comment by RiH-137** [comment]
I appreciate you raising this issue! I’ll merge your PR. I didn’t catch this mistake before, and your help is invaluable in improving the project.
