### ISSUE TITLE
Fix incorrect use of ReactDOM.render and migration to createRoot

### ISSUE THREAD

**Issue by adityaranjan2005** [RiH-137/Winta-1#5]
In the previous version of the code, ReactDOM.render was incorrectly used and caused an error. The latest React version requires using createRoot from react-dom/client for rendering. This update involves modifying the code to replace the deprecated ReactDOM.render with createRoot to ensure compatibility with React 18 and above.

**Comment by adityaranjan2005** [comment]
Suggested the PR

**Comment by RiH-137** [comment]
Thank you for pointing out the issue with the use of ReactDOM.render! I appreciate your suggestion to replace it with createRoot from react-dom/client, as required for React 18 and above. I’ll accept your PR to implement this change. I initially overlooked this update, and your input is crucial for ensuring compatibility. Thanks for your help in improving the code!
