### ISSUE TITLE
Refactor App component to include missing imports for routes

### ISSUE THREAD

**Issue by adityaranjan2005** [RiH-137/Winta-1#7]
The previous implementation of the App component was missing several imports for pages used in the Routes. As a result, navigating to certain routes resulted in errors due to the components not being defined. This update ensures all necessary components are properly imported, allowing for seamless navigation throughout the application.

**Comment by adityaranjan2005** [comment]
Suggested the PRs.

**Comment by RiH-137** [comment]
Thank you for highlighting the missing imports in the App component! I appreciate your thoroughness in identifying this issue. I’ll accept your PR to ensure that all necessary components are properly imported, which will resolve the navigation errors we were experiencing. I overlooked this detail in the previous implementation, and your contribution is essential for smooth navigation in the application. Thanks for your help!
